### ISSUE TITLE
pure HTTP proxy support to other JVMs running Jolokia without JSR 160?

### ISSUE THREAD

**Issue by jstrachan** [jolokia/jolokia#101]
We have an issue in hawtio in a browser using Jolokia's JavaScript client where we try to remotely connect to another JVM (on localhost on a different port) which uses a password protected jolokia war/servlet and we can't get the JavaScript client to work; we get all kinds of JavaScript errors due to authentication/authorisation headers & Origin issues; despite setting the user/pwd in the underlying Jolokia API and trying to set all the various CORS headers etc.

There's always the JSR 160 proxying; but then that has connection issues & doesn't do pipelining. So I was wondering about jolokia having a proxy servlet that would let it use a URL local to the current JVM which then redirects on the JVM side to a remote Jolokia URL? i.e. proxying purely at the HTTP/JSON layer in Jolokia (rather than delegating to JSR 160). I realise this only works if the remote JVM is running Jolokia; but thats fine in our case, we run it everywhere in Fuse by default.

There's a hawtio issue here:
https://github.com/hawtio/hawtio/issues/291

So I was wondering about using a URL something like this in the JavaScript jolokia client:
http://localhost:8080/jolokia/proxy/admin:admin@localhost/8181/jolokia say

which would then take the remainder of the servlet / filter URI and turn it into a JVM side proxy request to http:///admin:admin@localhost:8181/jolokia say. 

i.e. from the JavaScript/browser perspective, all the communication is with the JVM which served up the HTML/JS - with no cross domain / origin issues at all; then the JVM side does the proxy to the remote machines with Jolokia inside?

**Comment by jcordes73** [comment]
@jstrachan Does this fix work for you?

**Comment by rhuss** [comment]
Here the story from  https://jolokia.jira.com/browse/JOL-10 which is still a valid idea:

**As** a Jolokia user
**I want** to use a Jolokia agent also as a proxy to other Jolokia agents in an efficient way
**because** this allows for a single entry point from the 'outside' to all managed servers 'inside'

Similar to the JSR-160 proxy, there should be a way to pass on Jolokia request directly to another server. In contrast to the JSR-160 proxy, this mode should avoid parsing and recreating the request in order to get the target information. The idea is to use custom HTTP-Header for the routing information (so, even multiple 'hops' could become possible).

This feature would be solve various use cases:

* A monitoring solution for multiple servers which uses Jolokia's JavaScript integration. This way, hacks like JSONP or other solutins like CORS (see JOL-27) could be avoided to circumvent the same-origin policy.
* For JEE clusters, the admin server could proxy through to the managed servers giving a single view of the domain (described in weblogic lingo)

This story requires the modification of all clients in order to support the custom request and response headers in addition to the 'regular' request.

For simple authentication purposes, the credentials for the target server should be added obfuscated in the header.

#### ACCEPTANCE CRITERIA

* By using custom HTTP-Headers it should be possible to specify target hosts for the requests
* Specifying and using authentication for the target host should be possible
* Response Headers must indicate that the result is for a different server

**Comment by grgrzybek** [comment]
A lot has changed since 2015 about CORS/CSP ;) Jolokia client works perfectly when server is configured with proper [CORS headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin).

Jolokia should not (IMO) provide its own ProxyServlet and focus on the agent side.

Please reopen if you think I'm wrong ;)
