### ISSUE TITLE
Serialized Dates do not contain milliseconds

### ISSUE THREAD

**Issue by rasmuswlarsen** [jolokia/jolokia#181]
Hello,

When I return a java.util.Date object containing milliseconds, the resulting ISO-8601 date string does not contain any milliseconds.

More specifically, in org.jolokia.util.DateUtil.toISO8601(Date pDate,TimeZone pTimeZone) 

<pre>
SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
</pre>

should be changed to 

<pre>
SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
</pre>

Is it possible to change this?

**Comment by rhuss** [comment]
Currently I dare a bit to change this on the fly because it would break existing code which rely on the non-millisecond variant of the ISO-8601 format.

As an alternative you could use a `path` of value `time` which would return the epoch milliseconds (i.e. the milliseconds since 1.1.1970). This then could be easily converted to ISO-8601 with milliseconds on the client side. E.g. `http://localhost:8080/jolokia/read/mydomain:type=sth/dateAttribute/time`

Would this solution help you ?

Yet another alternative could be to add an additional 'path' (which indeed is interpreted as option in the case of a date) which then would return the millis in the ISO-8601 string as well (something like `time` maybe `iso8601millis` or `long`.

**Comment by rasmuswlarsen** [comment]
My mbean operation returns a complex data structure containing objects with Date objects. Will the 'time' path work there too?

**Comment by rhuss** [comment]
Yes, this should work, too. Simply add `time` as last part to the path.

**Comment by rasmuswlarsen** [comment]
I'm not sure where to do that. 

I'm calling from Javascript through the jolokia javascript client:

<pre>
var jolokiaRequest = {
	type : "exec",
	mbean : "myMBean",
	operation: "findObjects",
	arguments: [arg1, arg2]
};

jolokia.request(jolokiaRequest, {
	method: "post",
	success : function(response) {
		...
	},
	error : function(response) {
		...
	}
});
</pre>

**Comment by rhuss** [comment]
Ok, I see. This path thingy only works if use a path to pick a single date. I.e. you would have a `path` property in the request, and the response would contain only the part of the complex data structure where this path points to. So when using a path the `response.value` would be the time itself (i.e. the value the path is pointing to).

I guess, that doesn't help you much since you want to work on the whole object right ? (i.e. you need more than the date).

Let me think a bit about it. Maybe we can introduce a new query parameter which can influence the serialization of certain data types.

**Comment by rasmuswlarsen** [comment]
That would be nice. :-)

Furthermore, my response looks something like this:
<pre>
{
   "timestamp":1415267488,
   "status":200,
   "request":{
      "operation":"getMessageBodyForMessage(int)",
      "mbean":"com.csc.oip.platform:type=messageSearch",
      "arguments":[
         108
      ],
      "type":"exec"
   },
   "value":[
	   {
	      "updatedAt":"2014-11-06T10:51:28+01:00",
	      "id":1108,
        "charSet":"UTF-8",
        ...
	   },
	   {
	      "updatedAt":"2014-11-06T10:52:28+01:00",
	      "id":1109,
	      "charSet":"UTF-8",
	      ...
	   }
	 ]
}
</pre>

So <code>response.value</code> is not simple a date, it's an entire json object. And that is the object that I would like to use.

**Comment by rhuss** [comment]
I will think about this, but it will take probably a bit until it bubbles into a release.

In the meantime, there is a workaround which require repackaging the agent, though: Jolokia has a concept known as "simplifiers" which transform a Java Object in a (potentially simpler) value before transforming to JSON. These simplifiers are declared with their class names in `META-INF/simplifiers` and extrend [SimplifierExtractor](https://github.com/rhuss/jolokia/blob/master/agent/core/src/main/java/org/jolokia/converter/json/simplifier/SimplifierExtractor.java). And example of an simplifier is e.g. [FileSimplifier](https://github.com/rhuss/jolokia/blob/master/agent/core/src/main/java/org/jolokia/converter/json/simplifier/FileSimplifier.java)

So you could write your own Simplifier for a `Date` object which returns the value you want, package this class to your agent (e.g. within the WAR) and create a `META-INF/simplifiers` with the full qualified class name.

I know, that's a bit involved, but currently the only way that I can think of to solve the issue without introducing a new feature.

**Comment by grgrzybek** [comment]
I've just created a set of supporting classes for handling (in addition to `java.util.Date`:
* `java.util.Calendar`
* implementations of `java.time.Temporal`

Also I've added two new options to specify date format (and `java.time` formatter pattern) and the timezone for produced String values (if not available in the transformed object, like `java.time.Instant`).

I'll work on documentation and more tests tomorrow.

**Comment by grgrzybek** [comment]
PR #719 adds support for configurable datetime format which is used only only for `java.util.Date` fields, but also for `java.util.Calendar` and implementations of `java.time.Temporal`.

I didn't make it symmetrical (it never was), but we can additionally set these three:
* `java.time.Instant`
* `java.time.OffsetDateTime`
* `java.time.ZonedDateTime`

When writing on client side (to be unmarshalled at server side regardless of serialization format), we unmarshall these 3 values as Unix nano time.
Client doesn't have access to the configuration of `dateFormat` use by server side and also clients usually display the values when reading attributes.
