### ISSUE TITLE
Unable to deserialize multi-dimension arrays

### ISSUE THREAD

**Issue by Anerty** [jolokia/jolokia#212]
The StringToOpenTypeConverter doesn't seem to be able to handle arrays of more than one dimension, despite the fact that the ObjectToJsonConverter handles it just fine.

For example, an Integer[] works OK, but an Integer[][] will throw a java.lang.NumberFormatException when parsed.

The issue seems to lie in the org.jolokia.converter.object.ArrayTypeConverter.convertToObject method, which assumes the array only has one dimension and that the elements are of elementOpenType, which is wrong for arrays of dimension > 1.

It should check type.getDimension(), and handle the case where the dimension is > 1.

Minimal code to reproduce:

``` java
    StringToObjectConverter stoc = new StringToObjectConverter();
    ObjectToJsonConverter otjc = new ObjectToJsonConverter(stoc);
    StringToOpenTypeConverter stotc = new StringToOpenTypeConverter(stoc);
    Integer[] oneDim = new Integer[] { 1, 2 };
    // This access-restricted class is used to obtain the OpenType for arrays.
    final com.sun.jmx.mbeanserver.MXBeanMappingFactory f = com.sun.jmx.mbeanserver.MXBeanMappingFactory.DEFAULT;
    { // One dimension array, conversion works both ways
        System.out.println("one dim: " + Arrays.deepToString(oneDim));
        Object res = otjc.convertToJson(oneDim, null, JsonConvertOptions.DEFAULT);
        System.out.println("one dim to json: " + res);
        OpenType<?> type = f.mappingForType(oneDim.getClass(), f).getOpenType();
        System.out.println("one dim from json: " + Arrays.deepToString((Object[]) stotc.convertToObject(type, res)));
    }
    Integer[][] twoDims = new Integer[][] { oneDim, { 3, 4 } };
    { // Two dimension array, conversion only works one way
        System.out.println("two dims: " + Arrays.deepToString(twoDims));
        Object res = otjc.convertToJson(twoDims, null, JsonConvertOptions.DEFAULT);
        System.out.println("two dims to json: " + res);
        OpenType<?> type = f.mappingForType(twoDims.getClass(), f).getOpenType();
        System.out.println("two dims from json:" + Arrays.deepToString((Object[]) 
// This will throw a NumberFormatException
            stotc.convertToObject(type, res)));
    }
```

The StringToOpenTypeConverter.convertToObject() will throw the following exception for the two dimension array:
java.lang.NumberFormatException: For input string: "[1,2]"

**Comment by rhuss** [comment]
Thanks a for detailed report.

As stated in the documentation serializing / deserializing are indeed asymmetric with respect to their capabilities. Whereas serializing nearly always work (also for circular graphes etc.), deserialization is much more limited. In order to keep the agent as slim as possible (~300-400k currently), no full-featured JSON serializer like Jackson is intentionally not included. I try to push the deserialization caps as far as possible but it probably will never be perfect and will have its limits (like this one).

Currently my focus is on Jolokia 2.0 with JMX notification support, modularization and other enhancements. Since my resources are a bit limited currently I can't promise to get this fixed soon (which I think would be worth to fix).

But I'm open for PRs :) and will add it after some review. Please don't forget to read [this](git pull https://github.com/hughjfchen/jolokia.git master) if you consider to contribute a PR.
