### ISSUE TITLE
Release on npm?

### ISSUE THREAD

**Issue by kwesterfeld** [jolokia/jolokia#244]
I'm not sure who released jolokia-client on npm, but it would be great to have the JS library officially uploaded.  There is a jolokia-client on npm, but it's dependencies are all wrong, pulling in grunt as part of the client install.

**Comment by dalbani** [comment]
@kwesterfeld, I suppose you mean this package: https://github.com/jolokia-org/jolokia-client-javascript?

**Comment by kwesterfeld** [comment]
Yes that's correct

**Comment by tadayosi** [comment]
Fixed with #572. Now the JS client is provided as a npm package named `jolokia.js` (it is because other names are already used, such as "jolokia", "jolokia-client", and "jolokia-js" is too similar to existing name "jolokia.js" which we can use).

You can also try the early release to test it for your project. The JS client should be backward compatible with 1.x, so there should be no problems with using it with a Jolokia 1.x project.
https://www.npmjs.com/package/jolokia.js/v/2.0.0-dev.9
