### ISSUE TITLE
Option to remove POST request from response

### ISSUE THREAD

**Issue by ThomasRasmussen** [jolokia/jolokia#250]
Hi

We're about to use Jolokia to provide easy access to JVM statistics, and we are using POST interface (because we need to proxy to JMX) and the JMX listening requires authentication. When using ie. this 

`{"type": "read", "config": { }, "target": {"url": "service:jmx:rmi:///jndi/rmi://localhost:9090/jmxrmi", "password": "secretPassword", "user": "SecretUser"}, "mbean": "java.lang:type=MemoryPool,name=*", "attribute": "Usage" }`

Then the response contains the request including username and password. Since we are putting the output into Splunk, then we really would like to prevent the username/password from being printed.

Is it possible to disable this in the current (1.3.3) version or is it something that can be changed?

Thomas

**Comment by rhuss** [comment]
Unfortunately this is currently not possible since the request is [added always to the response](https://github.com/rhuss/jolokia/blob/master/agent/core/src/main/java/org/jolokia/backend/BackendManager.java#L431-L431), which is use for correlation e.g. in bulk request.

But I agree that this is a valid use case so that we should add this for one of the following versions.
