### ISSUE TITLE
Add Gson/JSonPath converters

### ISSUE THREAD

**Issue by svarcheg** [jolokia/jolokia#252]
Hello, 

Currently we are thinking about moving from JMX-RMI to jolokia for our servers management tooling. 

The migration is pretty smooth but i run into an issue, back in time we made an extensive usage of java beans returned/passed as a parameter to our jmx operations. Another constraint is that changing those objects sources is going to be overly complex and impossible for already released versions. 

Jolokia's parameter and return values serialization do a pretty good job for response value serialization but the parameter serialization does not work. 

So i was wondering if you can suggest any solution. 

After looking into the code i m thinking about adding an optional GSon/JSonPath serialization/deserialization.
An option could be added into JsonConvertOptions (aka useGson=true/false) and converters could be updated to handle that option properly. 

JSonPath is not a must have, but might be an optional replacement to jolokia's paths. 

Let me know what do you think. If you re ok i'll do a pull request. 

Regards, 

Vladimir

**Comment by rhuss** [comment]
Thanks for your question and for your interest. 

You are right, parameter serialization is limited (as explained [here](https://github.com/rhuss/jolokia/issues/212#issuecomment-136359434), too). However, Jolokia is not meant to be a full remoting framework and one design goals for the Jolokia agents is a small footprint (still below 500k). This also is possible because beside `json-simple` (20k) there are no dependencies. jsonpath alone has 200k (+ quite some transitive dependencies), gson also 230k (+ transitive dependencies), so that this would roughly double the size of the agent (or add 50% when only adding gson). So for Jolokia 1 I don't plan changes here.

But there is hope ;-) For Jolokia 2.0 it is planned that the serializer can easily be exchanged. Jolokia 2.0 is targeted for mid-year. It is already functional and contains all features of Jolokia 1.3.3. So maybe you want to give it a try ? In order to plugin in your own serializer all you need is to implement three methods of the [Serializer](https://github.com/rhuss/jolokia/blob/2.0/server/core/src/main/java/org/jolokia/server/core/service/serializer/Serializer.java) interfaces, whose single implementation is currently [JolokiaSerializer](https://github.com/rhuss/jolokia/blob/2.0/service/serializer/src/main/java/org/jolokia/service/serializer/JolokiaSerializer.java), the serializer you know from Jolokia.

If you want to give it a try with a GSon serializer implementation I would happily integrate it for Jolokia 2.0.

**Comment by svarcheg** [comment]
Thanks for the fast answer. 

I think we can perfectly go with 2.0, as out migration will be a long running process. 

I ll give a try with the Serializer interface and will be back to you with a pull request soon ;)

**Comment by rhuss** [comment]
Awesome :) BTW, if you want changes for the interface, we can discuss that. Nothing is finalized yet.

**Comment by svarcheg** [comment]
Finally I used jackson as it gives more control on how the json is generated. Is it ok for you? (I have also the gson one around). 

I would also like to have your opinion about couple of things: 

1/ current setInnerValue is designed in a way that it have to act directly on pOuterObject. what do you think about making it returning a object wrapping a pair [updated value, old value] instead? 

2/ I m not sure about how you want the library user to be able to use the new serializer. I was thinking about something like `jolokiaServer.addService(new JacksonSerializer(10));` before server start, but `JolokiaContextImpl#getMandatoryService`j seems to expect only one service per type. Wasn't the intent to use the service with the lowest priority value? 

Kind regards, 

Vladimir

**Comment by rhuss** [comment]
Thanks again for the PR, finally I was able to have a closer look (apologies for the delay).

With respect to your questions:

1. I'm not really convinced whether we need WriteRequestValues in order to return the new value which we already provide as part of the arguments. I simply dont get the benefit, see also the comment I added to the PR. But I probably missed a point (where the provided new value is different from the returned one). But if we would decide to go this route, we should then consistently update the whole interface to have the same usage pattern. Maybe we should also add a documentation what kind of objects are expected (JsonAware, plain objects, ...). I'm not so sure anymore ;-)

2. There is a lookup mechanism for services which should be used. So there won't be an active registration. Instead I recommend to move the GsonSerializer in an own Maven module and add a [services](https://github.com/rhuss/jolokia/blob/master/service/serializer/src/main/resources/META-INF/jolokia/services-default) descriptor which will be automatically picked up by the JVM + war Jolokia agent. If the service has a higher order (the last number) then the default service, it will be picked. Also you can exclude an already registered service by using a `!` prefix. See https://github.com/rhuss/jolokia/blob/2.0/server/core/src/main/java/org/jolokia/server/core/util/LocalServiceFactory.java for details of this syntax. The Osgi agent does a plain OsgiService lookup, so you would need to add an activator for this (see eg. https://github.com/rhuss/jolokia/blob/2.0/service/serializer/src/main/java/org/jolokia/service/serializer/osgi/SerializerServiceActivator.java)

The question is, where to place the module and how to wire the agents. For the module I suggest a new top-level directory `addon/` which we might move into an own project. The wiring is still an open issue. The vision is to have a *builder tool* which assembles the agent either via a WebUI or as a CLI (best served from a single, fat jar with all core services enabled). This is the comfort solution, but we could also go for a Maven profile based approach where every user can create her own agent by selecting one more profiles which simply add dependencies and enhanced e.g. the maven-shader-plugin configuration. 
I would leave this question open for the moment, but move the serializer class to an own agent. I'll add then a Maven profile, so that you can create your own custom agent including your serializer. The default agent distributed over Maven central will have a set of default services. As you know, one of the design goals is to keep the agent simple, to probably the old Jolokia serializer (which fits 90% of the use cases) will stay (the jackson dependencies added an 500k of deps which doubles the size of the agent).

Thoughts on this ?

**Comment by grgrzybek** [comment]
With #686 I was testing different JSON libraries found in this report: https://github.com/fabienrenaud/java-json-benchmark?tab=readme-ov-file#users-model

I rejected bloated, reflection/databind based libraries and also unmaintained or exotic ones.

I also checked GSON, but I decided to _not_ give it a deeper look:
* its maintainers moved to Kotlin-based https://github.com/square/moshi
* as with `org.json`, "JSON Object" is NOT a Map - it _contains_ a Map
* primitive values put into such map need to be wrapped with `com.google.gson.JsonPrimitive` which kind of disqualifies this library for Jolokia usage.

Also I was thinking about _pluggable serializer_ and while we may get back to this concept at some point, now, even with Jolokia 2, even `jolokia-server-core` library depends on JSON library's API.

If we want JSON serialization to be fully pluggable, `jolokia-server-core` would have to use `java.lang.Object` in too many places and we'd have to delegate to serializer service too often.

We can reopen if needed and there's time to spare.
