### ISSUE TITLE
Remote policyLocation with Basic-Auth

### ISSUE THREAD

**Issue by mweirauch** [jolokia/jolokia#276]
Hi,

does it look feasible to add support for Basic-Auth configuration when the `policyLocation` is retrieved from a remote location?

Background: We are using `spring-boot` with centralized configuration management via `spring-cloud-config`. The latter allows for serving "raw" files via it's interface. Think `jolokia-access.xml` served from the config server.

`spring-boot` allows setting the servlet init parameters. Thus the following setup:

```
jolokia.config.policyLocation=http://configserver/*/*/*/jolokia-access.xml
```

Unfortunately our config server is guarded with HTTP Basic-Auth and so the `RestrictorFactory` will get a `401` response and fail. Also the Java `UrlConnection` doesn't like URL tricks like `http://user:pass@host` so this isn't an option either. One would have to set the Basic-Auth headers itself.

A setup of the config server without Basic-Auth and jolokias Restrictor configured from remote works like a charme.

The config-server way would be my ideal solution instead of distributing a jolokia-access.xml with every application. (Be it by dependency, a spring boot starter or a build step for making sure the file is within the deployable artefact.)

**Comment by rhuss** [comment]
I could image to provide a functionality like this by parsing the URL for user & password and the setting the `Authorization:` header accordingly on our own. This would save some new configuration keys from which it already have too much (so that I always hesitate a bit to introduce new keys). 

However, I wonder whether this really make sense when used together with plain `http://`. After all `jolokia-access.xml` is about security and if you send it over http this can be easily forged with a man-in-the-middle attack. And since the password is send via plain text as well, this could be grabbed, too.

IMO it only makes sense to either use SSL (and then with server cert validation), or to put the restrictions really into the jar where it does not need to be loaded over the net during runtime.

BTW, you can easily write your own restrictor, too, which can do what you want. It depends on the agent your are using how to fire it up. You simply specify a classname with `restrictorClass` which needs to be in the classpath. You need to implement [Restrictor](https://github.com/rhuss/jolokia/blob/master/agent/core/src/main/java/org/jolokia/restrictor/Restrictor.java) and provide a constructor which takes a [Configuration](https://github.com/rhuss/jolokia/blob/master/agent/core/src/main/java/org/jolokia/config/Configuration.java) as single argument. 

You could easily inherit from [PolicyRestrictor](https://github.com/rhuss/jolokia/blob/master/agent/core/src/main/java/org/jolokia/restrictor/PolicyRestrictor.java) which takes an `InputStream` with its constructor. This is probably not well suited for inheritance, but I'm open to refactor this class to make it easier to inherit from. Happy also about any PR ;-)

**Comment by mweirauch** [comment]
Hi Roland,

thanks for the quick reply.

And indeed I forgot to mention the little detail that the config-client uses an SSL connection to the  config-server. The URL I posted was just local evaluation.

Writing my own Restrictor or shipping the `jolokia-access.xml` would mean a dependency (.jar) every deployable would have to attract. Dunno yet, if this fits our idea of a "shared-nothing" approach. Allthough this stance is arguably a bit troublesome in regards to a common set of basic functionality.

Also thanks for your proposal to parse the URL and apply Basic-Auth setup to the `UrlConnection`. I can't promise anything yet, but will come back to you as soon as we've decided on how we're going to proceed.

Thanks!
Michael

**Comment by mweirauch** [comment]
Hi again. Decision made.

I'd dare an implementation for the feature against 1.3.x/master if that is ok with you.

**Comment by rhuss** [comment]
Yeah, `master` is fine. As I said, would love an implementation without any extra configuration option (by using the standard URL encode credentials).

thanks !

**Comment by grgrzybek** [comment]
As @rhuss mentioned, `org.jolokia.server.core.service.api.Restrictor` is a great extension point and Spring (Boot) is a great platform to wire any kind of simple and complex applications.

Once we'd add support for basic auth credentials encoded within the URI for policy file location, someone may ask for digest auth, mutual TLS or OAuth2 Bearer token authentication.

So it's recommended for such complex (as yours) setup to implement your own `Restrictor`.
