### ISSUE TITLE
J4pRemoteException - invalid exception gets more info than error or invalid status

### ISSUE THREAD

**Issue by robstryker** [jolokia/jolokia#325]
In the code below, we can see that an invalid response receives the entire json, while an error status or an invalid status code don't.  

It'd be better to include the full json response in all 3 situations. 

     private static String generateErrorMessage(J4pRequest pJ4pRequest, JSONObject pJsonRespObject) {
        if( pJsonRespObject.get("error") != null ) {
               return (String) pJsonRespObject.get("error");
        }
        Object o = pJsonRespObject.get("status");
        if( o != null && !(o instanceof Long)) {
               return "Invalid status of type " + o.getClass().getName() + "('" + o.toString() + "') received";
        }
        return "Invalid response received: " + pJsonRespObject.toJSONString();
     }

**Comment by robstryker** [comment]
https://github.com/rhuss/jolokia/pull/326

**Comment by rhuss** [comment]
> In the code below, we can see that an invalid response receives the entire json, while an error status or an invalid status code don't.

Agreed that we unify it, but why not avoid including the whole JSON string as we already extract a lot of the content in specific fields. I feel this is quite redundant here (also having new lines and massive strings in execpetion.getMessage() is not really a good style).

What about removing the `toJSONString()` here and instead add an extra field `errorResponse` to the exception with a corresponding getter?

**Comment by apupier** [comment]
> What about removing the toJSONString() here and instead add an extra field errorResponse to the exception with a corresponding getter?

Are you suggesting to create a new Error Type which is some sort of "Other than Jolokia exception"?
In this case we can wrap the whole exception and reuse the error_value field, what do you think?

**Comment by rhuss** [comment]
I just would add to J4pRemoteExcetion  a method `getErrorResponse()` which returns the full JSONObject received in the constructor. The type in the case that it's a different error would `null`. I think that way we could examine the whole response (a client of the exception could still call `getErrorResponse().toJSONString()`

I believe that this is useful for situations where a different error is thrown by e.g. a proxy (well this error would need to be in JSON format, too. Otherwise we would not come that far to create the exception). So, in this case, I would not reuse any of the typed fields, specific to Jolokia errors. But leave the type and error empty so that the user of this class knows, that he would have to check the plain response and examine it on its own.

**Comment by rhuss** [comment]
Since we already expose JSONObject as part of J4pResponse, we should do it here the same way. It's more flexible for the user and she can still call `toJsonString()` herself.

**Comment by robstryker** [comment]
I updated the linked PR.

**Comment by grgrzybek** [comment]
Closing. #326 seems to be merged.
