### ISSUE TITLE
Issue with JmxAdapter Unit Tests on JDK 8 & 9

### ISSUE THREAD

**Issue by rhuss** [jolokia/jolokia#446]
There is an issue with a unit tests that are not working on older JDK: https://travis-ci.org/github/rhuss/jolokia/jobs/719557630

@skarsaune do you have an idea what is going wrong here ?

**Comment by skarsaune** [comment]
Yeah, couldn't find the comment on github, trying to reply by mail. Seemed
to build on last push. I have a script that runs the tests on jdk 7-14 on
my mac. Can try on my linux as well.

**Comment by rhuss** [comment]
Thanks ! I also found out that the OpenJDK 8 in Travis is different than mine that i have locally. E.g. i get NPE in unit tests on Travis but not locally.

**Comment by rhuss** [comment]
Maybe its worth to find out exactly the JDK version that travis is using ?

**Comment by skarsaune** [comment]
I have not been able to recreate identical problems. However I have looped over all jdks on my linux box. And in newer versions it fails due to a NamingException instead of a CommunicationException

`export` JAVA_HOME=/usr/lib/jvm/jdk1.8.0_261
mvn test-compile > /dev/null
for jdk in $(ls /usr/lib/jvm)
do
    export JAVA_HOME=/usr/lib/jvm/$jdk
    if [ -d $JAVA_HOME -a -f $JAVA_HOME/bin/java ]
    then
	mvn test --fail-at-end > /tmp/$jdk 2>/dev/null
	if [ $? -eq 0 ]
	then
	    echo "$jdk: PASS"
	else
	    echo "$jdk: FAIL"
	    cat /tmp/$jdk | grep -A 1 'sec  <<< FAILURE!'
	fi
    fi
done`

OUTPUT: 
`java-1.11.0-openjdk-amd64: FAIL
simpleWhiteListWithConfig(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.044 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
--
simpleWhiteListWithSysProp(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
java-1.13.0-openjdk-amd64: FAIL
simpleWhiteListWithConfig(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.032 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
--
simpleWhiteListWithSysProp(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
java-1.14.0-openjdk-amd64: FAIL
simpleWhiteListWithConfig(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.044 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
--
simpleWhiteListWithSysProp(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
java-11-openjdk-amd64: FAIL
simpleWhiteListWithConfig(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.044 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
--
simpleWhiteListWithSysProp(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
java-13-openjdk-amd64: FAIL
simpleWhiteListWithConfig(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.031 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
--
simpleWhiteListWithSysProp(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
java-14-openjdk-amd64: FAIL
simpleWhiteListWithConfig(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.028 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
--
simpleWhiteListWithSysProp(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
java-1.8.0-openjdk-amd64: FAIL
simpleWhiteListWithConfig(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.017 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
--
simpleWhiteListWithSysProp(org.jolokia.jsr160.Jsr160RequestDispatcherTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
java-8-openjdk-amd64: PASS
jdk1.8.0_202: PASS
jdk1.8.0_261: PASS`

**Comment by grgrzybek** [comment]
We've moved to GH actions and looks like the tests are very stable now.
