### ISSUE TITLE
Jolokia JS client does not support Long/BigInt

### ISSUE THREAD

**Issue by yuhusolutions** [jolokia/jolokia#495]
Hi, there is an issue with JS client library when the Java agent returns a numeric value greater than [Number#MAX_VALUE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_VALUE)

This affects JMX attributes/operations when the server returns a LONG value for instance.

The issues stems from [jolokia.js#L226 ](https://github.com/rhuss/jolokia/blob/c963d57751ef29ad924844ec6319fddabd8c2085/client/javascript/src/main/javascript/jolokia.js#L226) where the default JSON parser is used.

To preserve the value, would it be possible to use a custom parser to parse numeric values into BigInt (there are libs for this), or convert numeric value to quoted String?

See related issue at: https://github.com/hawtio/hawtio-integration/issues/108

**Comment by rhuss** [comment]
I see the problem, but unfortunately, I don't have any spare cycles to work on this. As long as we don't include any extra dependencies, I'm happy to help to integrate a pull request if someone is inclined to fix this. Another possible solution for your issue at hand and if you would have a chance to change the MBean that exports the long value, then you could also try to change this to a string type on your own.

**Comment by tadayosi** [comment]
Let me summarise the issue and proposed solution.
@grgrzybek @rhuss Please review this and let me know your thoughts.

**Problem**

The maximum raw number safely used in JS and JSON is [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER), which is `9007199254740991`. JS raw number lacks enough bits to represent numbers greater than the max value. A number larger than that is not just simply truncated but also may be rounded depending on the binary representation of it:
`90071992547409910` -> `90071992547409900`
`90071992547409930` -> `90071992547409940`

To handle numbers larger than the max there are two options:
1. Use string representation
2. Use [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) (`90071992547409910n` or `BigInt("90071992547409910")`)

The problem with the 2nd option is that `BigInt` is only supported since ES2020. The `jolokia.js` library is still based on ES5, so the 2nd option cannot be used for the `jolokia.js` library.

**Proposed solution**

Therefore, I propose to add a new Jolokia config option `serializeLong` (both global and per request), which prescribes the strategy for how to serialize values with type `long` from MBean attributes and operations. (We don't need to consider Java `BigInteger` values because it already has a [serialization strategy](https://jolokia.org/reference/html/manual/jolokia_protocol.html#serialization-response).)

The option would accept the following values:

1. `none` -- **Default,** and the original behaviours (do nothing) for backward compatibility.
2. `string` -- Always change `long` values to string in the returned JSON responses.
    Example:
    - `{ value: 90071992547409910 }` -> `{ value: "90071992547409910" }`
    - `{ value: 12345 }` -> `{ value: "12345" }`
3. `bigint` -- Always change `long` values to `BigInt` in the returned JSON responses.
    Example:
    - `{ value: 90071992547409910 }` -> `{ value: 90071992547409910n }`
    - `{ value: 12345 }` -> `{ value: 12345n }`

The 3rd option is provided for users who want to directly consume the JSON responses with their own >=ES2020 JS clients instead of using `jolokia.js`.

**Considerations**

For the 2nd option, we might want to instead follow the same serialisation with `BigInteger` like this:
```
{
  value: 90071992547409910
}
```
->
```
{
  value: {
    "long": "90071992547409910"
  }
}
```
 
WDYT?

Reference:
- https://jolokia.org/reference/html/manual/jolokia_protocol.html#serialization

**Comment by grgrzybek** [comment]
Oh, I didn't know about [`n` suffix](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt).

I assume the problem is not about deserialization of BigInts from JS in Java (we'd overflow Java's `long`), right?

So for Java (long) → JavaScript, I'd go with configuration option, but I would make `bigint` the default.

Also I'd think about Jolokia 2.1 with higher JS standard level... ES2015 is quite old ;) No safe browser nowadays stays at ES2015 support...
From Node.js point of view we also should not be restricted to ES2015 only...

**Comment by tadayosi** [comment]
Thanks. 

> assume the problem is not about deserialization of BigInts from JS in Java (we'd overflow Java's long), right?

Yes, so long as the original Jolokia issue.

> So for Java (long) → JavaScript, I'd go with configuration option, but I would make bigint the default.

Even after bumping ES version to ES2020 for `jolokia.js`, the other issue with using bigint is that `JSON.parse` doesn't support parsing bigint by default, and would need to add a custom `reviver` to correctly parse it. So we'd need to patch `jolokia.js` as well.
https://dev.to/benlesh/bigint-and-json-stringify-json-parse-2m8p

> Also I'd think about Jolokia 2.1 with higher JS standard level... ES2015 is quite old ;) No safe browser nowadays stays at ES2015 support...
> From Node.js point of view we also should not be restricted to ES2015 only...

That's actually an interesting idea. I'm not opposed to it. Let's see if we can upgrade ES version to ES2020 for Jolokia 2.1.

For reference:
- https://github.com/jolokia/jolokia/issues/576

**Comment by grgrzybek** [comment]
> JSON.parse doesn't support parsing bigint by default

oh, indeed...

> And user apps that use older jolokia.js should be broken with the new Jolokia agent version

definitely - we should bump protocol version: https://github.com/jolokia/jolokia/blob/main/HOWTO_RELEASE.md#jolokia-protocol-version-change

**Comment by rhuss** [comment]
Well, I'm okay with anything. Since we already have numerical values being serialized as string (Java's BigInteger), I would not have an issue serializing long as strings, too, as long as this is consistent (i.e. all `long` are returned the same way)

A configuration option seems legit, with the default being `none` (i.e., if nothing is specified, the old behavior is kept) for backward compatibility until we change the protocol version.

**Comment by tadayosi** [comment]
Follow-up on my comment https://github.com/jolokia/jolokia/issues/495#issuecomment-2123922187 and pull req #693.

- I initially proposed the `serializeLong` option with 3 values: `none`, `string` and `bigint`. But after closer investigation and review from @grgrzybek the final impl only allows the 2 values: `number` (default) and `string`. The option `bigint` turned out to be awkward to support for the following reasons:
    - The JSON library we currently use (json-simple) cannot handle the BigInt notation: #686
    - If we include the BigInt notation (`12345n`) to the JSON response, it would become something that diverges from the standard JSON specification: https://www.json.org/json-en.html
- The final impl #693 also includes a new request parameter `dataType` (with value: `json` (default) or `text`) only for `jolokia.js`, which can influence the `ajaxParams.dataType` and allow the client to return the response as text instead of parsing it with `JSON.parse()`. It's intended to provide the JS client users with yet another way to deal with the long values issue.

**Comment by grgrzybek** [comment]
Great - thanks @tadayosi !
