### ISSUE TITLE
Tomcat 10 / JakartaEE  not supported

### ISSUE THREAD

**Issue by KoushikMaity** [jolokia/jolokia#544]
class org.jolokia.http.AgentServlet cannot be cast to class jakarta.servlet.Servlet (org.jolokia.http.AgentServlet and jakarta.servlet.Servlet are in unnamed module of loader 'app')

Latest version of Jolokia still using javax so it is not compatible with tomcat 10.

Exception thrown in StandardWrapper.java of org.apache.catalina.core.

Please release compatible version for tomcat10.

**Comment by RustyDust** [comment]
While waiting for pr #540 to get applied, you can try to add to your Tomcat's `context.xml`:

``` xml
...
<Context>
   ...
   <Loader  jakartaConverter="TOMCAT" />
</Context>
```

wfm,ymmv

**Comment by rui-zhou-phx** [comment]
does it mean jolokia doesn't support spring boot 3.x?

**Comment by tadayosi** [comment]
@rui-zhou-phx Right now, Spring Boot 3.x has dropped its Jolokia endpoint because Jolokia 1.x isn't compatible with Jakarta EE yet. We are working on Jolokia 2.0 which is based on Jakarta EE 9/10 https://github.com/jolokia/jolokia/discussions/555. Once it's released we can restore support for Spring Boot 3.x.

**Comment by grgrzybek** [comment]
I'm closing this one in favor of #451, which has several external mentions (e.g., from Spring Boot)
