### ISSUE TITLE
Bug with partial shading of `org.json.simple` in `jolokia-jvm:1.7.2`

### ISSUE THREAD

**Issue by kuzma-deretuke-db** [jolokia/jolokia#569]
```
package org.jolokia.jvmagent.handler;
...
public class JolokiaHttpHandler implements HttpHandler {
    ...
    // org.json.simple.JSONAware
    private JSONAware executeGetRequest(ParsedUri parsedUri) {
        // org.jolokia.shaded.org.json.simple.JSONAware
        return requestHandler.handleGetRequest(...);
    }
```

**Result**

Class cast exception in runtime.
Version 1.6.2, worked without problems.

**Links**

* [JolokiaHttpHandler.java](https://github.com/jolokia/jolokia/blob/v1.7.2/agent/jvm/src/main/java/org/jolokia/jvmagent/handler/JolokiaHttpHandler.java)
* [shading in pom.xml](https://github.com/jolokia/jolokia/blob/v1.7.2/agent/jvm/pom.xml#L120)

**Comment by kuzma-deretuke-db** [comment]
```
[TSB-1] Sep 4 10:38:14.710 DEBUG - GET /jolokia/exec/bb-testing-server-1%20uat18-uk:name=testingMbean,type=TestingM<TRUNCATED> [200  OK] () [] [httpserver] [] [jolokia-14]
[TSB-1] Sep 4 10:38:14.713 DEBUG - ServerImpl.Exchange (5) [java.lang.NoSuchMethodError: 'org.jolokia.shaded.org.json.simple.JSONObject org.jolokia.http.HttpRequestHandler.handleThrowable(java.lang.Throwable)'
        at org.jolokia.jvmagent.handler.JolokiaHttpHandler.doHandle(JolokiaHttpHandler.java:245)
        at org.jolokia.jvmagent.handler.JolokiaHttpHandler$1.run(JolokiaHttpHandler.java:192)
        at org.jolokia.jvmagent.handler.JolokiaHttpHandler$1.run(JolokiaHttpHandler.java:190)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
        at org.jolokia.jvmagent.handler.JolokiaHttpHandler.doHandleAs(JolokiaHttpHandler.java:190)
        at org.jolokia.jvmagent.handler.JolokiaHttpHandler.handle(JolokiaHttpHandler.java:178)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:71)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:848)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:815)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
] [httpserver] [] [jolokia-14]
```

**Comment by grgrzybek** [comment]
@kuzma-deretuke-db I'd have to see one more thing - the configuration of your application - especially the classpath that's used.

In my case, all the classes were loaded from `jolokia-jvm` jar and when checking its `org.jolokia.http.HttpRequestHandler` class I see:
```
$ javap /data/tmp/HttpRequestHandler.class
Compiled from "HttpRequestHandler.java"
public class org.jolokia.http.HttpRequestHandler {
  public org.jolokia.http.HttpRequestHandler(org.jolokia.config.Configuration, org.jolokia.backend.BackendManager, org.jolokia.util.LogHandler);
  public org.jolokia.shaded.org.json.simple.JSONAware handleGetRequest(java.lang.String, java.lang.String, java.util.Map<java.lang.String, java.lang.String[]>);
  public org.jolokia.shaded.org.json.simple.JSONAware handlePostRequest(java.lang.String, java.io.InputStream, java.lang.String, java.util.Map<java.lang.String, java.lang.String[]>) throws java.io.IOException;
  public java.util.Map<java.lang.String, java.lang.String> handleCorsPreflightRequest(java.lang.String, java.lang.String);
  public org.jolokia.shaded.org.json.simple.JSONObject handleThrowable(java.lang.Throwable);
  public org.jolokia.shaded.org.json.simple.JSONObject getErrorJSON(int, java.lang.Throwable, org.jolokia.request.JmxRequest);
  public void checkAccess(java.lang.String, java.lang.String, java.lang.String);
  public java.lang.String extractCorsOrigin(java.lang.String);
  static {};
}
```

At first glance looks like your classpath contains both jolokia-jvm and jolokia-core, where the same class is:
```
$ javap /data/tmp/HttpRequestHandler.class
Compiled from "HttpRequestHandler.java"
public class org.jolokia.http.HttpRequestHandler {
  public org.jolokia.http.HttpRequestHandler(org.jolokia.config.Configuration, org.jolokia.backend.BackendManager, org.jolokia.util.LogHandler);
  public org.json.simple.JSONAware handleGetRequest(java.lang.String, java.lang.String, java.util.Map<java.lang.String, java.lang.String[]>);
  public org.json.simple.JSONAware handlePostRequest(java.lang.String, java.io.InputStream, java.lang.String, java.util.Map<java.lang.String, java.lang.String[]>) throws java.io.IOException;
  public java.util.Map<java.lang.String, java.lang.String> handleCorsPreflightRequest(java.lang.String, java.lang.String);
  public org.json.simple.JSONObject handleThrowable(java.lang.Throwable);
  public org.json.simple.JSONObject getErrorJSON(int, java.lang.Throwable, org.jolokia.request.JmxRequest);
  public void checkAccess(java.lang.String, java.lang.String, java.lang.String);
  public java.lang.String extractCorsOrigin(java.lang.String);
  static {};
}
```

**Comment by kuzma-deretuke-db** [comment]
```
% ../../mvnw dependency:tree -Dincludes=org.jolokia

[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ jmx-utils ---
[INFO] <project.groupId>:jmx-utils:jar:<project.version>
[INFO] +- org.jolokia:jolokia-spring:jar:1.6.2:compile
[INFO] |  +- org.jolokia:jolokia-jvm:jar:1.6.2:compile
[INFO] |  \- org.jolokia:jolokia-jmx:jar:1.6.2:compile
[INFO] \- org.jolokia:jolokia-core:jar:1.6.2:compile
```

**Comment by grgrzybek** [comment]
`dependency:tree` is handy, but in fact, the order of JARs on classpath is important - you need to show how your application is actually run - we don't know if it's running in servlet container, from shell script or using any other method ;)

**Comment by kuzma-deretuke-db** [comment]
I have no control over classpath. this is a shared library used by multiple internal projects (700+).

**Comment by grgrzybek** [comment]
So you have to decide between jolokia-core and jolokia-jvm, which simply contains jolokia-core inside.
jolokia-agent.jar is used with `-javaagent` option, while jolokia-core (and e.g., jolokia-spring) can be normally added to a classpath.

**Comment by kuzma-deretuke-db** [comment]
I removed hawtio from dependencies. And now dependency tree looks like this:
```
[INFO] \- org.jolokia:jolokia-spring:jar:1.7.2:compile
[INFO]    +- org.jolokia:jolokia-jvm:jar:1.7.2:compile
[INFO]    |  \- org.jolokia:jolokia-core:jar:1.7.2:compile
[INFO]    \- org.jolokia:jolokia-jmx:jar:1.7.2:compile
```
why? both `-core` and `-jvm` in classpath?

**Comment by grgrzybek** [comment]
It's up to you to construct the classpath. Indeed, Jolokia has jolokia-spring → jolokia-jvm → jolokia-core dependency, but if you start jolokia using agent (`-javaagent`) you don't have to put jolokia-core additionally to your classpath.

**Comment by kuzma-deretuke-db** [comment]
> I have no control over classpath. this is a shared library used by multiple internal projects (700+). and it should work regardless of the classpath order.

I guess original (intended) use for `jolokia-jvm` and `jolokia-spring` was to configure it as JVM agent, however as for now `jolokia-spring` could be and actually used as maven dependency in our projects. Moreover `jolokia-spring-1.7.2.jar!/META-INF/spring.schemas` and `jolokia-spring-1.7.2.jar!/META-INF/spring.handlers` shout this approach is correct.

You are using shade plugin to build `jolokia-jvm`. However publish ORIGINAL pom.xml in the released artefact, while correct way would be to publish dependency-reduced pom.xml instead. And because of incorrect released pom.xml in `jolokia-jvm` maven brings BOTH `jolokia-core` and `jolokia-jvm` into final classpath.

**Comment by grgrzybek** [comment]
I've added a comment under #398 - I finally had some time to investigate. Thanks for notice about dependency-reduced-pom. This is indeed a problem and I'm just changing the dependencies for upcoming Jolokia 2.0.
Then I can fix the issue in Jolokia 1.7.x.

**Comment by grgrzybek** [comment]
cc: @rhuss @tadayosi @apupier

Let me highlight the issue:
* jolokia-support-spring uses classes from jolokia-agent-jvm and it can't be changed (`org.jolokia.support.spring.SpringJolokiaAgent` extends `org.jolokia.jvmagent.JolokiaServer`)
* before 1.7.0, [jolokia agent](https://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.6.2/) was available in two forms:
  * with `agent` classifier (embedding shaded json library and some jolokia deps)
  * without `agent` classifier (just classes from the agent)
* after 1.7.0, [jolokia agent](https://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.7.0/) had only no-classifier version with shaded classes

The classifier change was related to change from maven-assembly-plugin to maven-shade-plugin (see e7ab408b). But also it broke (see this issue) jolokia-support-spring → jolokia-agent-jvm dependency, because before 1.7.0, jolokia-support-spring depended on no-classifier agent without shaded classes.

`createDependencyReducedPom` of maven-shade-plugin is the way to express dependencies better, because what's available in Maven repo after deployment is the processed POM without the dependencies that were actually shaded.

The problem however occurs in IDE / non-IDE scenarios. In pure Maven build, the dependencies are used after shading, however in IDE it's before shading (which isn't even performed).

That's why now jolokia-support-spring tests work in IDE, but fail in `mvn` with: ```Exception in thread "jolokia-0" java.lang.NoSuchMethodError: 'org.jolokia.shaded.org.json.simple.JSONObject org.jolokia.server.core.http.HttpRequestHandler.handleThrowable(java.lang.Throwable)'
	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.doHandle(JolokiaHttpHandler.java:184)
	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.handle(JolokiaHttpHandler.java:109)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:852)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:819)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
```

The solution would be to get back to pre 1.7.0 behavior and have jolokia-agent-jvm deployed in two flavors:
* with `agent` classifier (and shaded classes)
* without classifier

Then no Jolokia module should depend on the `agent` classified version and `jolokia-agent-jvm-2.0.0-agent.jar` (...) should be used as standalone agent, in which case no other Jolokia dependency should be present on classpath.

WDYT?

**Comment by tadayosi** [comment]
@grgrzybek I fail to follow your discussion. It appears to me that Jolokia 2.0 has already applied what you proposed (going back to pre 1.7.0). What am I missing?
https://repo1.maven.org/maven2/org/jolokia/jolokia-agent-jvm/2.0.0-M4/

**Comment by grgrzybek** [comment]
M4 rather had what pre 1.7.0 had, because the history is:
* 1.6.x - maven-assembly-plugin with `<id>agent</id>` in assembly descriptor - so we have `-agent` classifier
* 1.7.x - maven-shade-plugin without classifier - so we have just `jolokia-jvm-1.7.2.jar` with shaded classes inside
* 2.0.0.M4 - maven-shade-plugin with `<shadedArtifactAttached>true</shadedArtifactAttached>` and `<shadedClassifierName>agent</shadedClassifierName>`

So actually, the only concern I have is that `jolokia-agent-jvm-2.0.0-agent.jar` looks weird...

**Comment by grgrzybek** [comment]
What do you think about:
* `jolokia-agent-jvm-2.0.0-standalone.jar` - JAR to be used in `-javaagent` with embedded jolokia-server-core, jolokia-server-detector, jolokia-service-serializer, jolokia-service-jmx, jolokia-service-discovery, jolokia-service-history, jolokia-service-jsr160, jolokia-service-notif-pull, jolokia-service-notif-sse and with shaded json-simple (`org.json.simple.**` → 
* `jolokia-agent-jvm-2.0.0-jar` - JAR which is brought by Maven dependency of `org.jolokia:jolokia-agent-jvm` without classifier - this is important for jolokia-support-spring which has this dependency. And when shaded version is used we have ClassCastException, because there would be two json-lib versions (shaded - in non-classifier version of jvm agent and non-shaded from transitive dependency on jvm agent)

That's why I think 1.7.0 approach is bugged (this this #569 issue) and we need classifier+shaded version for standalone usage and non-classifier+non-shaded+non-embedded version for Maven usage.

And `standalone` sounds better for me than `agent` classifier - WDYT?

**Comment by tadayosi** [comment]
@grgrzybek I personally don't see issue with the name `jolokia-agent-jvm-2.0.0-agent.jar`, but if you wouldn't prefer then please go ahead and rename it to `-standalone.jar`. But `-standalone.jar` sounds a bit like we could run it with `java -jar ...` (but we really coudn't).

**Comment by grgrzybek** [comment]
good point ;)

**Comment by rhuss** [comment]
I know that the first agent part in the name reflects the directory hierarchy (I always liked that because you can derive from the name of the artefact where it comes from), but I wonder whether we should reconsider this choice as it feels redundant a bit. E.g. `jolokia-jvm-2.0.0-standalone.jar` and `jolokia-jvm-2.0.0.jar`.

Or, maybe evenbetter we just use `jolokia-agent-jvm-2.0.0-javaagent.jar` ? (this directly reflects the `-javaagent` options in the name and should reduce the confusion)

**Comment by grgrzybek** [comment]
> Or, maybe evenbetter we just use `jolokia-agent-jvm-2.0.0-javaagent.jar` ? (this directly reflects the `-javaagent` options in the name and should reduce the confusion)

Naming is hard, but you are a winner here ;) It's now clear:
* `jolokia-agent` part means it's Jolokia Agent (similar to WAR and OSGi agents)
* `javaagent` means it's a Jolokia Agent to be used with `-javaagent`

Can't be better and clearer ;)

**Comment by grgrzybek** [comment]
I'd like to wrap up this issue.

Jolokia 1.7.0 incidentally caused problems when moving from maven-assembly-plugin to maven-shade-plugin, because the Jolokia Agent JVM without classifier is both shaded and has Maven dependencies, so every time you declare Maven dependency on [jolokia-jvm-1.7.2](https://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.7.2/jolokia-jvm-1.7.2.pom) you introduce conflicts and potential `java.lang.NoSuchMethodError`.

The _only_ thing we can do for 1.7.x is to recommend exclusion:
```xml
<dependency>
    <groupId>org.jolokia</groupId>
    <artifactId>jolokia-jvm</artifactId>
    <version>1.7.2</version>
    <exclusions>
        <exclusion>
            <groupId>org.jolokia</groupId>
            <artifactId>jolokia-core</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

Because otherwise we'd break minor-version compatibility.

Mind that it's fixed in Jolokia 2, which is an easy upgrade from 1.x (except `javax` → `jakarta` migration).
