### ISSUE TITLE
Create new `jolokia-fetch.js` JS client library

### ISSUE THREAD

**Issue by tadayosi** [jolokia/jolokia#580]
Follow-up of #575.

I've learnt that replacing `$.ajax` with Fetch API in `jolokia.js` to remove dependency to jquery would bring destructive, backward incompatible changes to the JS client library. We should instead create a new JS client `jolokia-fetch.js` which is based only on Fetch API and supports async mode only, so that we can provide users with an option not to depend on jQuery for their apps.

`jolokia-simple.js` should support both verions of JS client.

**Comment by grgrzybek** [comment]
It's rather that Fetch API is async-only, while jolokia.js was sync+async (I wasn't aware of this ;)).

And we'll have 2 options now - jolokia.js or jolokia-fetch.js (naming is hard ;)) - correct me if I'm wrong @tadayosi please.

**Comment by tadayosi** [comment]
Yes, Grzegorz is right. My finding is that Fetch API only provides async processing unlike jQuery ajax.
```js
const j4p = new Jolokia('/jolokia')
const response = j4p.request({ ... }) // sync mode
```
If we want to support both sync/async with the new `jolokia.js` we'd need to use good old `XMLHttpRequest` as well, but I don't think it's worth the effort.

Now the modern JS/TS support `async` / `await` notations, for the new JS client it would be nicer that it only supports async by returning `Promise`.

**Comment by rhuss** [comment]
I'm totally fine with ditching the sync support.

**Comment by grgrzybek** [comment]
one of the benefits o moving to [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is more fine grained handling of credentials.
For xhr, we can use `withCredentials` option to include credentials for cross-origin requests. However with using same-origin request, this option is ignored and credentials are always attached if available.
With Fetch API, there's `credentials` option which [can be set to](https://developer.mozilla.org/en-US/docs/Web/API/fetch#credentials) three options (`omit`, `same-origin`, `include`), so we can prevent attaching the credentials for same-origin requests.

Having an option to prevent adding the credentials allows us to control whether or not native browser popup for basic credentials is displayed and we can handle it differently (like custom UI).

**Comment by grgrzybek** [comment]
I have some update for this case.
After months of struggling with _modern JavaScipt_ (where _modern_ means _newer than few months ago_), I felt confident enough to do some experiments.

First, here's a state of JavaScript nowadays from Jolokia point of view:
* because current `jolokia.js` depends on jQuery and browser in general, we don't have to bother (much) about _Jolokia running in node.js_
* we're waaaaaaay past the time where we had to support _old_ browsers (IE7, Firefox 3, ...). https://caniuse.com/es6-module shows that we have strong ESM support in all browsers.
* Most web applications (like the ones based on React) use bundlers (webpack, esbuild, ...) to process NPM packages into browser-friendly code

Having these assumptions, I started very promising work on `client/javascript-esm` Jolokia module which would:
* switch from `xhr` to Fetch API
* be implemented with ESM (EcmaScript Modules)
* be testable with `jest`
* be published as NPM module(s) in ESM format, but also in `UMD` format

I bit of clarification about `UMD` - currently `jolokia.js` library is wrapped in CJS/AMD/browser friendly [IIFE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function#using_an_immediately_invoked_function_expression_iife) like this:

```javascript
(function (root, factory) {
    if (typeof define === "function" && define.amd) {
        // AMD. Register as an anonymous module.
        define(["jquery"], factory);
    } else if (typeof module === "object" && module.exports) {
        // Node. Does not work with strict CommonJS, but
        // only CommonJS-like environments that support module.exports,
        // like Node.
        var jquery = require("jquery");
        ...
    } else {
        // Browser globals
        root.Jolokia = factory(root.jQuery);
    }
}(typeof self !== "undefined" ? self : this, function (jQuery) {
...
```

But (I used my code-archeology perks), I found exactly where the above structure comes from - check out this template: https://github.com/umdjs/umd/blob/master/templates/returnExportsGlobal.js. It even has the same comment ;)
```javascript
// Node. Does not work with strict CommonJS, but
// only CommonJS-like environments that support module.exports,
// like Node.
```

For a short while I was looking at `jolokia-cubism.js` to check whether we can use something newer and I played a bit with direct usage of [D3](http://d3js.org/). It was very good experience, because I found it uses https://rollupjs.org/ as the bundler.

And here's my experiment with Jolokia, written using pure ESM syntax.

It produces these files (for now):
```
jolokia-2.1.0.js
jolokia-2.1.0.min.js
jolokia-2.1.0.mjs
jolokia-cbsm-2.1.0.js
jolokia-cbsm-2.1.0.min.js
jolokia-cbsm-2.1.0.mjs
```

It uses this `rollup.config.js` (fragment):
```javascript
const configJolokia = {
  input: "src/jolokia.js",
  plugins: nodeResolve(),
  output: [
    {
      ...defaultOutput,
      file: `dist/jolokia-${pkg.version}.js`,
    },
    {
      ...defaultOutput,
      file: `dist/jolokia-${pkg.version}.min.js`,
      plugins: [ terser() ]
    },
    {
      ...defaultOutput,
      file: `dist/jolokia-${pkg.version}.mjs`,
      format: "esm"
    }
  ]
}
```

quite clear - one input, three different outputs.

And it produces (:drum:) JS files with this IIFE wrapper:
```javascript
(function (global, factory) {
typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('./jolokia.js'), require('d3')) :
typeof define === 'function' && define.amd ? define(['exports', './jolokia', 'd3'], factory) :
(global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.JolokiaCbsm = global.JolokiaCbsm || {}, global.Jolokia, global.d3));
})(this, (function (exports, Jolokia, d3) { 'use strict';
...
```

See - it's _the same_ IIFE (for CJS/AMD/browser) as Jolokia currently uses!

What's more, we can configure with Rollup config like this:
```javascript
const defaultCbsmOutput = {
  ...defaultOutput,
  name: "JolokiaCbsm",
  globals: {
    [jolokiaModuleURL]: "Jolokia",
    d3: "d3"
  }
}
```

which variables should be bundled and which should be passed _from global scope_:
```javascript
factory(global.JolokiaCbsm = global.JolokiaCbsm || {}, global.Jolokia, global.d3)
```

This makes Rollup really perfect solution to produce both ESM files and JS files which can be used directly in `<script src="..."></script>` like we're doing today.

Having additionally real ESM Jolokia files, we can consume them with any bundler (like webpack).

I don't want to go the way with a dead end, but for now (took me few hours to almost migrate entire jolokia.js) it looks very promising.

Oh - and having https://jsdoc.app/ inside `jolokia.js` gives me type checking, IDE (Idea) support and TypeScript generation of `types.d.js`! See https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html:
> [With TypeScript 3.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#--declaration-and---allowjs), TypeScript added support for generating .d.ts files from JavaScript using JSDoc syntax.

**Comment by tadayosi** [comment]
Thanks Grzegorz for sharing your ideas and progress. Let me reply to some of them.

> - because current jolokia.js depends on jQuery and browser in general, we don't have to bother (much) about Jolokia running in node.js

In fact, the current `jolokia.js` can already be used with Node.js. The `jolokia.js` itself doesn't have a dependency to browser DOM. So, while I admit there should be few Node.js users who use `jolokia.js` with it already, I think we should not exclude the idea of running a Jolokia JS client library in Node.js as well.
https://github.com/tadayosi/jolokiajs-test-ts/blob/main/src/basic.ts

> For a short while I was looking at jolokia-cubism.js to check whether we can use something newer and I played a bit with direct usage of [D3](http://d3js.org/).

Cubism.js has been abandoned for many years already. I personally think we should just deprecate and remove `jolokia-cubism.js` from our JS client libraries. Probably it'd be better to start a new library with some modern chart library separated from this main project if needed.

> It was very good experience, because I found it uses https://rollupjs.org/ as the bundler.

The whole direction looks great. I think, if we go the path of using a bundler like rollupjs, it'd be better to use TypeScript instead of keeping using pure JavaScript for the client. Once we introduce a bundler there's no more direct relationship between the source and the dist code, so it shouldn't matter if we use JS or TS in the source code. Also, if we use TS, then generating the `.d.ts` type definitions can be a lot more reliable and straightforward than using JsDoc.

I remember why we keep using JS for the `jolokia.js` is because Roland prefers to keep the source in the distribution as is for the JS client library and we respect the decision. For the new client `jolokia-esm` or `jolokia-fetch`, maybe we are allowed for a different choice from scratch. But I think we should still keep the original `jolokia.js` and `jolokia-simple.js` for a while.

**Comment by grgrzybek** [comment]
We'll tackle releasing and frontend-maven-plugin configuration later. For now, we simply have (unpublished) jolokia client library using Fetch API and Promises.
Also docs are needed.
