### ISSUE TITLE
Potential bug in JmxRemoteAdapter#invoke()

### ISSUE THREAD

**Issue by tadayosi** [jolokia/jolokia#594]
During addressing #592, IntelliJ suggested this line of code has a potential problem, where `Arrays.equals()` on different types of objects resolves them as different.

https://github.com/jolokia/jolokia/blob/8152c76587b901608dd7016857d1c636a2cca5aa/client/jmx-adapter/src/main/java/org/jolokia/client/jmxadapter/RemoteJmxAdapter.java#L464-L469

 The correct code should be what is commented out there. However, when applying the fix, the tests start to fail. We need to fix the tests as well.

**Comment by grgrzybek** [comment]
`org.jolokia.client.jmxadapter.JmxBridgeTest#testRecordingSettings()` is problematic and IDEA shows a real problem here :)

`getRecordingOptions` operation on `jdk.management.jfr:type=FlightRecorder` MBean is this:
```
operation = {javax.management.MBeanOperationInfo@4880} "javax.management.MBeanOperationInfo[description=getRecordingOptions, name=getRecordingOptions, returnType=javax.management.openmbean.TabularData, signature=[javax.management.MBeanParameterInfo[description=p0, name=p0, type=long, descriptor={}]], impact=unknown, descriptor={}]"
 arrayGettersSafe: boolean  = true
 description: java.lang.String  = {@4902} "getRecordingOptions"
 descriptor: javax.management.Descriptor  = null
 impact: int  = 3
 name: java.lang.String  = {@4901} "getRecordingOptions"
 signature: javax.management.MBeanParameterInfo[]  = {javax.management.MBeanParameterInfo[1]@4900} 
 type: java.lang.String  = {@4899} "javax.management.openmbean.TabularData"
```

when `Arrays.equals()` compares `java.lang.String[]` with `javax.management.MBeanParameterInfo[]` it returns false, so later, `org.jolokia.client.jmxadapter.ToOpenTypeConverter#recursivelyBuildOpenType()` gets `typeFromMBeanInfo=null` and simply uses `rawValue instanceof JSONObject` check and this fragment:

```java
final String[] keys = new String[structure.size()];
final OpenType<?>[] types = new OpenType[structure.size()];
int index = 0;
for (Object element : structure.entrySet()) {
    @SuppressWarnings("unchecked")
    Map.Entry<String, Object> entry = (Entry<String, Object>) element;
    keys[index] = entry.getKey();
    types[index++] = recursivelyBuildOpenType(name + "." + entry.getKey(), entry.getValue(),
        typeFromMBeanInfo);
}
if (types.length == 0) {
    throw new InvalidOpenTypeException("No subtypes for " + name);
} else {
    return new CompositeType("complex", "complex", keys, keys, types);
}
```

while it should really be `javax.management.openmbean.TabularType`.

By iterating over this JSONObject:
```
structure = {org.json.simple.JSONObject@4931}  size = 7
 {@4974} "duration" -> {@4975} "0"
 {@4976} "disk" -> {@4977} "true"
 {@4978} "maxAge" -> {@4979} "0"
 {@4980} "name" -> {@4981} "1"
 {@4982} "destination" -> null
 {@4983} "maxSize" -> {@4984} "0" 
 {@4985} "dumpOnExit" -> {@4986} "false"
```

Jolokia (`org.jolokia.client.jmxadapter.ToOpenTypeConverter#recursivelyBuildOpenType()`) simply creates a `javax.management.openmbean.TabularType` with `java.util.Map<String, String>` type/description and a row type which is a `CompositeType` with two keys:
* key
* value

I'm changing the test case

**Comment by tadayosi** [comment]
Wow, very quick. I was about to look into it myself. Thank you!
