### ISSUE TITLE
Replace json-simple with different JSON library

### ISSUE THREAD

**Issue by tadayosi** [jolokia/jolokia#686]
I noticed that Jolokia is still based on the old json-simple library for JSON manipulations. json-simple is no longer maintained, of which the last release was more than ten years ago. We should migrate to a newer and maintained JSON library such as [JSON-java](https://github.com/stleary/JSON-java). JSON-java seems to have quite similar API to json-simple and appears mostly compatible, so migration shouldn't be so hard.

There are outstanding issues with json-simple as well, for instance:
- https://github.com/jolokia/jolokia/issues/226

Hopefully they might be resolved by migrating to JSON-java as well.

**Comment by grgrzybek** [comment]
:+1:
we definitely need something simple - no data binding, no execution, just json - hashmap.
I'll check next week (PTO today).

**Comment by tadayosi** [comment]
One more motivation to move away from json-simple to JSON-java is that, while json-simple cannot parse JSON with native BigInt notation (it throws a parser exception):
```
{ "bigint": 12345678901234567890n }
```
JSON-java can parse it without problems (it parses the value to string "12345678901234567890n").

**Comment by rhuss** [comment]
Happy to migrate, one of the reasons I've chosen json-simple was because of its size, since I wanted the agent to be as small as possible (below 100k was once a goal, now probably more like below 600k). I would still keep size as a criterion when selecting a new library

**Comment by tadayosi** [comment]
Good to know that size is an important factor for the agent. Comparing json-simple with JSON-java:
- json-simple: ~24k
- JSON-java: ~78k

https://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/
https://repo1.maven.org/maven2/org/json/json/20240303/

So switching to JSON-java would increase the agent size by ~54k. We might want to examine all the dependencies once to see if there's any room for shrinking the size.

**Comment by davsclaus** [comment]
In camel-core we have jsooner - it has no dependency at all
https://github.com/apache/camel/tree/main/tooling/camel-util-json

**Comment by tadayosi** [comment]
Oh, `camel-util-json` is only ~40k. It's smaller than JSON-java.
https://repo1.maven.org/maven2/org/apache/camel/camel-util-json/4.6.0/

**Comment by grgrzybek** [comment]
Hmm, no dependencies, but leads to Camel parent which may bring `<dependencyManagement>`...

**Comment by davsclaus** [comment]
You can copy the code over and build it as part of hawtio

**Comment by tadayosi** [comment]
> Hmm, no dependencies, but leads to Camel parent which may bring `<dependencyManagement>`...

Oh really?  Is that how Maven works even if we don't specify the dependency as pom?

**Comment by davsclaus** [comment]
You can also maybe shade the camel JAR

**Comment by grgrzybek** [comment]
> > Hmm, no dependencies, but leads to Camel parent which may bring `<dependencyManagement>`...
> 
> Oh really? Is that how Maven works even if we don't specify the dependency as pom?

I didn't mean Camel's managed dependencies to be _imported_ to Jolokia managed dependencies, or impact the `mvn dependency:tree` - so it shouldn't be a problem ;)

**Comment by davsclaus** [comment]
Just a heads-up that we have an issue with using jolokia in camel jbang (due to some shading it seems) so I had to fix this by using reflection
https://issues.apache.org/jira/browse/CAMEL-20847

https://github.com/apache/camel/commit/0c3a28572a6932ec36a1014debfdcafea582eb4d

**Comment by grgrzybek** [comment]
I added a comment to https://issues.apache.org/jira/browse/CAMEL-20847

The vertx-related stacktrace doesn't say much, but the screenshot shows shaded version of json-simple being used. This should not happen, unless you have `org.jolokia:jolokia-agent-jvm` artifact with `javaagent` classifier on the CLASSPATH.

See https://jolokia.org/migration.html#jolokia_jvm_agent_module

**Comment by grgrzybek** [comment]
Things to consider:
* json-simple had base `JSONAware` class for `JSONObject` and `JSONArray`, org.json doesn't have this
* json-simple could store null values in a map, org.json doesn't do it

**Comment by grgrzybek** [comment]
There's something weird going on...
I was able to move _entire_ Jolokia codebase from `com.googlecode.json-simple:json-simple:1.1.1` to `org.json:json:20240303` and all the tests pass.

I have to admit that `json-simple` JSONObject implementing a Map interface is real saver and I had to do some type juggling with `org.json`. But I did it.

I have an Artemis (2.35.0-SNAPSHOT) with Hawtio 4 and Jolokia 2 running (this branch: https://github.com/andytaylor/activemq-artemis/tree/artemis-console-plugin) and I used IDEA profiler (JFR based). What's more, I've created 10K Artemis queues which added 20K MBeans with similar name pattern.

Now, plain `{"type":"list"}` request results in a response weighting 234MB (non-formatted JSON) and ...
* it takes 15 seconds with `json-simple`
* it takes 11 seconds with `org.json`

...

First I thought there's something wrong, but both JFR and poor-profiling show same results:

`json-simple` and `org.jolokia.server.core.backend.BackendManager#callRequestDispatcher()`:
```
GRGR: requestDispatcher.dispatch: 830 ms
GRGR: serialize: 7664 ms
```
![image](https://github.com/jolokia/jolokia/assets/306565/35b58bf6-6a67-4196-ad30-4f44b2e6511a)

`org.json` and `org.jolokia.server.core.backend.BackendManager#callRequestDispatcher()`:
```
GRGR: requestDispatcher.dispatch: 937 ms
GRGR: serialize: 1 ms
```
![image](https://github.com/jolokia/jolokia/assets/306565/3aef256b-18e3-4c47-9b6e-bb8a9c830833)

**Comment by grgrzybek** [comment]
`handleSecurely()` is faster with `org.json`, because I already use the version with #706 fixed. `java.util.Stack` is synchronized.

**Comment by grgrzybek** [comment]
#708 is a huge PR that fully moves Jolokia from `com.googlecode.json-simple:json-simple` to `org.json:json`. However I'm not completely certain that we _should_ move...

`org.json:json` pros and cons comparing to `json-simple`:
* :heavy_plus_sign: it's generics aware
* :heavy_plus_sign: it's maintained
* :heavy_plus_sign: it has better API (`opt` and `get`)
* :heavy_plus_sign: it supports JSON standard better. For example with json-simple we could parse this problematic JSON: https://github.com/jolokia/jolokia/blob/v2.0.3/client/java/src/test/java/org/jolokia/client/J4pClientTest.java#L63-L67 (no commas between object entries)
* :heavy_minus_sign: it seems to be slower when writing values (a bit more time spent on escaping
* :heavy_minus_sign: (though probably it's from JSON standard, but I don't think so) it changes types a lot - I had to make some tests use integers instead of longs. Also when double is e.g., `3.0` it's changed to `3`, so it becomes integer. Also doubles become BigDecimals...
* :heavy_minus_sign: in `json-simple` JSONObject **is** a Map. In `org.json` JSONObject **contains** a Map (same for arrays / lists, though JSONArray in `org.json` is `Iterable`)
* :heavy_minus_sign: `org.json` handles nulls differently - if you put null value to a map and serialize, the key is missing. with `json-simple` it's null - that's why you have these `opt` / `get` methods...

For performance related tasks I will be working on both branches:
* https://github.com/jolokia/jolokia/tree/main
* https://github.com/jolokia/jolokia/tree/use-org.json

and I'll provide more research data.

**Comment by grgrzybek** [comment]
My mistake with early return from `org.jolokia.service.serializer.json.ObjectToJsonConverter#extractObject()` made me realize something - Jolokia is getting full, proper JSON from all these MBeanInfo instances (in `list()` operation) and is copying **entire structure** which is later serialized.

Initially I simply returned the top-level JSONObject (with `org.json` implementation) and the result was correct. Jolokia however _may_ use `path` parameter to return part of the structure - that's why the deep copy.

**But it's not needed when there's no `path` parameter**! It'd make `json-simple` also faster ;)

Now, the discussion #705 is about new major _Jolokia protocol version_ and I have more reasons to optimize `list()` operation - `maxDepth`, `maxCollectionSize` and `path` are not sufficient.

WDYT @tadayosi @rhuss ?

**Comment by tadayosi** [comment]
@grgrzybek It makes sense to me, but what would you specifically suggest on json-simple vs org.json with the insight?

**Comment by rhuss** [comment]
Sorry for my ignorance, I'm a bit disconnected here. What is the background of org.json. Who is backing it and is there a strong long-term support likely ? Also, is it growing or are people considering it stable and maintain it (which I would prefer, to avoid code blow up in the future or introducing of new security related bugs).

Otherwise, I don't insist on json-simple and the size difference should not be an argument (25k difference is less than 5% or the latest agents AFAIR).

The only thing that makes me some headaches is the different semantics around null value, which could lead to difficult to detect bugs. Also, the different conversions of types could be problematic.

**Comment by grgrzybek** [comment]
What's my suggestion? I'd say, for now, I'm 62% for keeping `json-simple` and 38% for moving to `org.json` ;)

All Jolokia tests pass, which means there should be no surprises, but the issue with `list()` (where I simply didn't do any processing of the tree, but got the same result) shows that it's not an ultimate indicator.

`org.json` has some security coverage - there was https://nvd.nist.gov/vuln/detail/CVE-2022-45688 for this library. I'm  not sure if `json-simple` is even a subject of such security research.

I can't clearly show the numbers about `org.json` vs `json-simple` usage

* https://github.com/fangyidong/json-simple/commits/master/ - updated 3 years ago (minor change) and then 10 years ago. 743 GH stars
* https://github.com/stleary/JSON-java/commits/master/ - updated quite regularly, 4.5K GH stars

`json-simple` (wrongly) parses JSON like:
```json
{"error_type":"errorType""status":500"error_value":{"test":"ok"}}
```

and `org.json` correctly throws parsing exception.

OTOH this null handling _may_ be an issue for java client, but because `org.jolokia.client.request.J4pResponse#jsonResponse()` would return new object with different API, it'd be (kind of) justified.

Mind that most of my performance optimization is not tiny tweaking of escaping, but to make `list()` return optimized responses (thus new protocol version) - see #564.

As I said - I'm rather collecting pros and cons and we don't have to decide yet. When I'll work on serious profiling / optimization / protocol changes, I'll do more research about the API change impact.

**Comment by rhuss** [comment]
> OTOH this null handling may be an issue for java client, but because org.jolokia.client.request.J4pResponse#jsonResponse() would return new object with different API, it'd be (kind of) justified.

I'm also thinking about non-Java clients that are typeless. They would find out the semantic change just during runtime.

**Comment by grgrzybek** [comment]
> > OTOH this null handling may be an issue for java client, but because org.jolokia.client.request.J4pResponse#jsonResponse() would return new object with different API, it'd be (kind of) justified.
> 
> I'm also thinking about non-Java clients that are typeless. They would find out the semantic change just during runtime.

This doesn't affect JS clients, as semantically there's no difference. Thanks for feedback! As I said - nothing's decided yet. I enjoy checking this, I learn profiling tools (it's an investment on my side) and I'll also check Johnzon.

**Comment by grgrzybek** [comment]
Hmm, I checked Johnzon for a while. It's actually an implementation of https://jakarta.ee/specifications/jsonp/ and the object model looks nice, but API doesn't (comparing to what we have)...

There's nice hierarchy of objects:
```
JsonValue (jakarta.json)
    JsonNumber (jakarta.json)
        JsonDoubleImpl (org.apache.johnzon.core)
        JsonLongImpl (org.apache.johnzon.core)
        JsonNumberImpl (org.apache.johnzon.core)
    JsonString (jakarta.json)
        JsonStringImpl (org.apache.johnzon.core)
    JsonStructure (jakarta.json)
        JsonArray (jakarta.json)
            EmptyArray (jakarta.json)
            JsonArrayImpl (org.apache.johnzon.core)
        JsonObject (jakarta.json)
            EmptyObject (jakarta.json)
            JsonObjectImpl (org.apache.johnzon.core)
    JsonValueImpl (jakarta.json)
```

But you can't simply have `JsonObject` and add values there... Everything is done through a _builder_ and `build()` method returns unmodifiable map/list... You can create new object based on previous one:
```java
@Override
public JsonObjectBuilder createObjectBuilder(JsonObject jsonObject) {
    return builderFactory.get().createObjectBuilder(jsonObject);
}
```

it actually does a shallow copy, but still - there's already too many builders and factories. I think it's a no-go for Jolokia.

**Comment by grgrzybek** [comment]
And I somehow feel reluctant to try https://github.com/alibaba/fastjson ...

**Comment by grgrzybek** [comment]
google/gson#1821 says:
> […] but if I understand it correctly they (or one of them) quit their job at Google and are now working at Square where they are working on https://github.com/square/moshi, a competitor of Gson.

and:
> In short, it seem Gson is already in maintenance mode because it was mostly replaced by "moshi", a new project build by some of the same contributor with less short-comming than Gson

The problem is that Moshi seems to be Kotlin-based (like okio, okhttp from squareup) and brings in entire Kotlin runtime as Maven dependencies. Unacceptable.

For Gson - while it's quite nice and has easy to use adapters between JSON and various types (like maps, lists and also objects (reflection)), what is unacceptable for Jolokia is that all primitive types are wrapped within `com.google.gson.JsonPrimitive` - again - it's fine if you start new project, but not for Jolokia.

**Comment by grgrzybek** [comment]
I think we may have a winner!
I used @davsclaus suggestion, created https://issues.apache.org/jira/browse/CAMEL-20948 and apache/camel#14747 and checked the timing.

The env I used was the same as before - Artemis with 20K queues and Hawtio 4 + Jolokia 2.
The response is for `list()` request, which weights 234MB (no formatting)

* `json-simple` response: 7 seconds
* `org.json` response: 9.8 seconds
* `camel-util-json` response: 5.1 seconds

While it took me some time to try API change to `org.json`, with `camel-util-json` it was very quick - with Camel JSON library we also have `JsonObject` extending `Map` and common `org.apache.camel.util.json.Jsonable` base just as in `json-simple`.
After several fixes to make `jolokia-server-core` actually compile, all tests passed _immediately_ without any changes that were needed for `org.json`!

I only migrated (locally) the modules used by Artemis (to check the performance impact):
* jolokia-server-core
* jolokia-service-serializer
* jolokia-service-jmx
* jolokia-service-jsr160

but I already have a favorite candidate!

WDYT @rhuss @tadayosi ?

* `org.apache.camel/camel-util-json` is 41kB
* `org.json/json` is 78kB
* `com.googlecode.json-simple/json-simple` is 23kB

**Comment by tadayosi** [comment]
@grgrzybek I agree. It looks like camel-util-json is the best option!

**Comment by grgrzybek** [comment]
The only problem I see is that there are quite frequent Camel releases and from Jolokia perspective we'd have new Camel versions without changes to this single jar. And if we stay with single Camel version, Camel users using Jolokia may have different Camel versions (when not using Camel BOM...)

**Comment by davsclaus** [comment]
You can also copy the source code and have your own hawtio-json jar - this would be nicer IMHO - then its pure hawtio.

**Comment by grgrzybek** [comment]
> You can also copy the source code and have your own hawtio-json jar - this would be nicer IMHO - then its pure hawtio.

s/hawtio/jolokia/:)

**Comment by grgrzybek** [comment]
All tests pass with `camel-util-json`. I have to polish this a bit and check how Jolokia Client may be improved.

**Comment by grgrzybek** [comment]
Summarizing the test, moving to `camel-util-json` was much easier and less problematic than moving to `org.json:json`. Also Camel's library is much faster than both `org.json` and `json-simple`.

The only _issue_ I see is that `camel-util-json` is parsing numbers into `BigDecimal` values. There are great methods to retrieve such values as longs, doubles, etc., but it is something that has to be handled carefully.

Also we don't have the problems with `null` values as with `org.json`.

**Comment by davsclaus** [comment]
We can maybe improve camel-util-json to parse into Long, Integer more naturally instead of BigDecimal. I guess we can check if the number of digits is > MAX_LONG / MAX_INT we can then use big decimimal otherwise use the best Int vs Long instead.

**Comment by grgrzybek** [comment]
I see the reasons of quite easy migration - both parsers are generated by jflex it seems:
* https://github.com/apache/camel/tree/db4956b5bacbb1b1984695fc18aaa6706ff9969d/tooling/camel-util-json/src/main/java/org/apache/camel/util/json
* https://github.com/fangyidong/json-simple/tree/master/src/main/java/org/json/simple/parser

But Camel's version seems more sophisticated. However Camel only has:
```java
case 2: {
    java.math.BigDecimal val = new java.math.BigDecimal(yytext());
    return new Yytoken(Yytoken.Types.DATUM, val);
}
```
in the lexer, json-simple has:
```java
case 2: 
          { Long val=Long.valueOf(yytext()); return new Yytoken(Yytoken.TYPE_VALUE, val);
          }
```

That's why Jolokia was casting everything to `long`...

I'll have to check how #495 fits with this change.

**Comment by grgrzybek** [comment]
@gnodet, may I ask you if you generated JSON parser from the grammar or did you take the code from other place? See https://github.com/apache/camel/tree/db4956b5bacbb1b1984695fc18aaa6706ff9969d/tooling/camel-util-json/src/main/java/org/apache/camel/util/json

**Comment by grgrzybek** [comment]
Ideally I'd like to have:
* `jolokia-json` library being a dependency of `jolokia-client-java`, `jolokia-server-core`, ...
* classes like `org.jolokia.json.JsonObject` being used by `org.jolokia.client.J4pClient` (being part of its API)
* no direct dependency on Camel
* easy development in IDE (so I see the classes without previous `mvn clean install`) - without shading and similar magic

I could use maven-dependency-plugin to unpack `sources` artifact from `camel-util-json`, but then I can't do package renaming.
Moving from `org.json.simple.JSONObject` to `org.apache.camel.util.json.JsonObject` is (from Jolokia PoV) a  change from one (unmaintained) API to new (perfectly maintained) API - but both are similarly _external_.

If we move - why not move to `org.jolokia.json`?

**Comment by tadayosi** [comment]
+1 to move to `org.jolokia.json`.

**Comment by grgrzybek** [comment]
PR: #712

**Comment by grgrzybek** [comment]
I'd like to summarize this long discussion.

1. Jolokia got stuck with https://code.google.com/archive/p/json-simple/ which didn't have releases since 2012 (1.1.1)
2. This project was moved to https://github.com/fangyidong/json-simple (just because closing code.google.com)
3. Because there were no releases, there was a fork at https://github.com/cliftonlabs/json-simple/ which had [some releases between 2016 and 2022](https://repo1.maven.org/maven2/com/github/cliftonlabs/json-simple/)
4. @davsclaus suggested to use https://github.com/apache/camel/commits/camel-4.7.0/tooling/camel-util-json library and it really was the fastest of the three _simple_ libraries (json-simple, org.json, camel-util-json)
5. I confirmed with the profiler that camel-util-json is slim, fast and suitable for Jolokia, but it'd tie Jolokia API (client, server) to `org.apache.camel` packages and versioning cycles
6. So I tried typical _lazy_ approach with maven-shade-plugin, but I wanted to have both sources _brought in_ into Jolokia, but also some shading (maven-shade-plugin) as we have with `org.json.simple` packages
7. So I [dug deeper](https://github.com/apache/camel/commit/7ed581ab175a409ead254e9017f9e8257fa74bdb#diff-c63bddb34d552c06e8a5f1a8987f1305bfe77d2a3dd5c77f7566cbf35887570a) and found that Camel's `camel-util-json` started with a copy of `com.github.cliftonlabs/json-simple/2.1.2` with build-time replacement of `public class JsonObject extends HashMap` with `public class JsonObject extends LinkedHashMap` - Camel wanted ordered JSON objects!
8. Seeing `camel-util-json` faster than `json-simple` I knew that there must be some kind of evolution of the common underlying library (`json-simple`)
9. That's how I found these grammars:
   * https://github.com/fangyidong/json-simple/blob/master/doc/json.lex
   * https://github.com/cliftonlabs/json-simple/blob/master/src/main/lex/jsonstrict.lex
10. Camel's `camel-util-json` is simply based on a library that uses a lexer generated from very simple (and complete) JSON grammar!
11. That's why it took me about a day to craft `org.jolokia/jolokia-json` module with [own JSON grammar](https://github.com/jolokia/jolokia/blob/ee077d5/json/src/main/jflex/jsonstrict.flex) which I enjoyed commenting. It is not a copy of the above grammars - I wrote it looking at these, but also checking [current JSON RFC 8259](https://datatracker.ietf.org/doc/html/rfc8259)
12. After generating a lexer using https://www.jflex.de/ and its maven plugin, I simply wrote own JSON parser started by creating objects/interfaces that Jolokia code failed to find after removing `com.googlecode.json-simple/json-simple` library from the classpath. Then I simply created the required methods, implemented them and voila!

The rest is history. I could then profile it again, find some bottlenecks, [forbid leading and trailing commas](https://github.com/jolokia/jolokia/blob/ee077d5de81ed459dd324c8a6497180de78c4516/json/src/test/java/org/jolokia/json/parser/ParserObjectsTest.java#L59-L67) within JSON arrays / objects and review some parsing/serialization code (#713).

When calling `list()` on Artemis 2.35.0 with Hawtio 4 and Jolokia 2, I went down from:
```
GRGR: requestDispatcher.dispatch: 695
GRGR: serialize: 7223
GRGR: sendResponse: 7485
```

to:
```
GRGR: requestDispatcher.dispatch: 767
GRGR: serialize: 4196
GRGR: sendResponse: 3399
```

the above operations are 3 stages of performing `list()` request. >2x decrease of serialization time!

cc: @tadayosi @rhuss
